-- ============================================================
-- Mahfazati — BCNF PostgreSQL Schema
-- ============================================================

drop table if exists public.notification    cascade;
drop table if exists public.user_reward     cascade;
drop table if exists public.reward          cascade;
drop table if exists public.transaction     cascade;
drop table if exists public.prepaid_card    cascade;
drop table if exists public.branch          cascade;
drop table if exists public.wallet          cascade;
drop table if exists public.merchant        cascade;
drop table if exists public.customer        cascade;
drop table if exists public.profiles        cascade;

create table public.profiles (
    user_id      int       generated by default as identity primary key,
    auth_uid     uuid      not null unique references auth.users(id) on delete cascade,
    name         text      not null,
    phone_number text      not null,
    user_type    text      not null check (user_type in ('customer', 'merchant')),
    created_at   timestamptz not null default now()
);

create table public.customer (
    user_id  int  primary key references public.profiles(user_id) on delete cascade
);

create table public.merchant (
    user_id       int   primary key references public.profiles(user_id) on delete cascade,
    merchant_code text  not null unique,
    service_type  text  not null,
    latitude      double precision,
    longitude     double precision
);

create table public.wallet (
    wallet_id int            generated by default as identity primary key,
    user_id   int            not null unique references public.profiles(user_id) on delete cascade,
    balance   numeric(15,3)  not null default 0.000 check (balance >= 0),
    points    int            not null default 0       check (points >= 0),
    status    text           not null default 'active' check (status in ('active', 'frozen')),
    created_at timestamptz   not null default now(),
    updated_at timestamptz   not null default now()
);

create table public.branch (
    branch_id    int   generated by default as identity primary key,
    merchant_id  int   not null references public.merchant(user_id) on delete cascade,
    branch_name  text  not null,
    qr_code      text  not null unique,
    location_url text,
    latitude     double precision,
    longitude    double precision,
    is_active    boolean not null default true
);

create table public.prepaid_card (
    card_id    int            generated by default as identity primary key,
    code       text           not null unique,
    amount     numeric(15,3)  not null check (amount > 0),
    is_used    boolean        not null default false,
    used_by    int            references public.profiles(user_id) on delete set null,
    used_at    timestamptz,
    expires_at timestamptz    not null
);

create table public.transaction (
    transaction_id     int            generated by default as identity primary key,
    sender_wallet_id   int            not null references public.wallet(wallet_id),
    receiver_wallet_id int            not null references public.wallet(wallet_id),
    transaction_type   text           not null check (transaction_type in ('transfer', 'payment')),
    amount             numeric(15,3)  not null check (amount > 0),
    payment_method     text           not null check (payment_method in ('NFC', 'QR', 'direct')),
    status             text           not null default 'pending' check (status in ('pending', 'completed', 'failed')),
    branch_id          int            references public.branch(branch_id) on delete set null,
    notes              text,
    transaction_date   timestamptz    not null default now(),
    check (sender_wallet_id <> receiver_wallet_id)
);

create table public.reward (
    reward_id       int   generated by default as identity primary key,
    merchant_id     int   not null references public.merchant(user_id) on delete cascade,
    reward_type     text  not null check (reward_type in ('discount', 'prize')),
    required_points int   not null check (required_points > 0),
    description     text,
    discount_text   text,
    is_active       boolean not null default true
);

create table public.user_reward (
    user_reward_id int          generated by default as identity primary key,
    user_id        int          not null references public.profiles(user_id) on delete cascade,
    reward_id      int          not null references public.reward(reward_id) on delete cascade,
    redeemed_at    timestamptz  not null default now(),
    points_spent   int          not null check (points_spent > 0),
    status         text         not null default 'pending' check (status in ('pending', 'redeemed', 'cancelled'))
);

create table public.notification (
    notification_id int          generated by default as identity primary key,
    user_id         int          not null references public.profiles(user_id) on delete cascade,
    message         text         not null,
    notif_type      text         not null default 'general' check (notif_type in ('transaction', 'reward', 'system', 'general')),
    is_read         boolean      not null default false,
    sent_at         timestamptz  not null default now()
);

-- indexes
create index idx_wallet_user         on public.wallet(user_id);
create index idx_branch_merchant     on public.branch(merchant_id);
create index idx_transaction_sender  on public.transaction(sender_wallet_id);
create index idx_transaction_receiver on public.transaction(receiver_wallet_id);
create index idx_transaction_date    on public.transaction(transaction_date desc);
create index idx_reward_merchant     on public.reward(merchant_id);
create index idx_user_reward_user    on public.user_reward(user_id);
create index idx_notification_user   on public.notification(user_id);

-- trigger: auto-create profile + wallet + customer on auth signup
create or replace function public.handle_new_user()
returns trigger as $$
declare
  v_user_id int;
begin
  insert into public.profiles (auth_uid, name, phone_number, user_type)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'name', ''),
    coalesce(new.raw_user_meta_data ->> 'phone_number', ''),
    coalesce(new.raw_user_meta_data ->> 'user_type', 'customer')
  )
  returning user_id into v_user_id;

  insert into public.wallet (user_id) values (v_user_id);

  if coalesce(new.raw_user_meta_data ->> 'user_type', 'customer') = 'customer' then
    insert into public.customer (user_id) values (v_user_id);
  end if;

  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- trigger: auto-update wallet.updated_at
create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger wallet_updated_at
  before update on public.wallet
  for each row execute function public.set_updated_at();

-- RLS
alter table public.profiles      enable row level security;
alter table public.customer      enable row level security;
alter table public.merchant      enable row level security;
alter table public.wallet        enable row level security;
alter table public.branch        enable row level security;
alter table public.prepaid_card  enable row level security;
alter table public.transaction   enable row level security;
alter table public.reward        enable row level security;
alter table public.user_reward   enable row level security;
alter table public.notification  enable row level security;

create policy "profile: own" on public.profiles
  for all using (auth.uid() = auth_uid);
create policy "customer: own read" on public.customer
  for select using (auth.uid() = (select auth_uid from public.profiles where user_id = customer.user_id));
create policy "merchant: public read" on public.merchant
  for select using (true);
create policy "wallet: own read" on public.wallet
  for select using (auth.uid() = (select auth_uid from public.profiles where user_id = wallet.user_id));
create policy "branch: public read" on public.branch
  for select using (true);
create policy "transaction: participant" on public.transaction
  for select using (
    auth.uid() in (
      select p.auth_uid from public.wallet w
        join public.profiles p on p.user_id = w.user_id
      where w.wallet_id in (sender_wallet_id, receiver_wallet_id)
    )
  );
create policy "reward: public read" on public.reward
  for select using (true);
create policy "user_reward: own" on public.user_reward
  for all using (auth.uid() = (select auth_uid from public.profiles where user_id = user_reward.user_id));
create policy "notification: own" on public.notification
  for all using (auth.uid() = (select auth_uid from public.profiles where user_id = notification.user_id));
